#!/bin/sh

case "$1" in
	start)
		echo "My script called at the start of the system" ;;
	stop)
		echo "My script called at the stop of the system" ;;
	restart|reload)
		$0 stop
		$0 start ;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac
